# Generated by Django 6.0.7 on 2026-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer_a', models.CharField(max_length=200)),
                ('answer_b', models.CharField(max_length=200)),
                ('answer_c', models.CharField(max_length=200)),
                ('answer_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('category', models.CharField(choices=[('world_cup', 'World Cup'), ('champions_league', 'Champions League'), ('players', 'Players & Legends'), ('clubs', 'Football Clubs'), ('euro', 'European Championship'), ('history', 'Football History')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
    ]
